export const ErrorCode = {
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INVALID_UUID: 'INVALID_UUID',
  INVALID_DATE_RANGE: 'INVALID_DATE_RANGE',
  MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
  PLAN_NOT_FOUND: 'PLAN_NOT_FOUND',
  MEMBERSHIP_NOT_FOUND: 'MEMBERSHIP_NOT_FOUND',
  CHECK_IN_NOT_FOUND: 'CHECK_IN_NOT_FOUND',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  ACTIVE_MEMBERSHIP_EXISTS: 'ACTIVE_MEMBERSHIP_EXISTS',
  MEMBERSHIP_ALREADY_CANCELLED: 'MEMBERSHIP_ALREADY_CANCELLED',
  MEMBER_DELETED: 'MEMBER_DELETED',
  PLAN_INACTIVE: 'PLAN_INACTIVE',
  MEMBERSHIP_EXPIRED: 'MEMBERSHIP_EXPIRED',
  MEMBERSHIP_NOT_ACTIVE: 'MEMBERSHIP_NOT_ACTIVE',
  NO_ACTIVE_MEMBERSHIP: 'NO_ACTIVE_MEMBERSHIP',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export interface ValidationErrorDetail {
  field: string;
  message: string;
  code: string;
}

export interface ApiError {
  code: ErrorCode;
  message: string;
  details?: ValidationErrorDetail[];
  stack?: string;
}
